"""Adiciona pdf_filename para limpeza de arquivos

Revision ID: 1a2a10e7a8e1
Revises: 551e4771cfbf
Create Date: 2025-07-20 15:03:33.495864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2a10e7a8e1'
down_revision = '551e4771cfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado', schema=None) as batch_op:
        batch_op.drop_column('pdf_filename')

    # ### end Alembic commands ###
