"""Cria a tabela inicial de chamados

Revision ID: 551e4771cfbf
Revises: 
Create Date: 2025-07-19 22:09:06.485448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551e4771cfbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_solicitante', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('codigo_fornecedor_pdf', sa.String(length=50), nullable=True),
    sa.Column('dados', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('hora_envio', sa.DateTime(), nullable=True),
    sa.Column('hora_conclusao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chamado')
    # ### end Alembic commands ###
